ALTER TABLE users 
ADD COLUMN IF NOT EXISTS stripeIdentityVerified BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS stripeIdentitySessionId VARCHAR(255),
ADD COLUMN IF NOT EXISTS stripeIdentityVerifiedAt TIMESTAMP,
ADD COLUMN IF NOT EXISTS stripeIdentityPaymentIntentId VARCHAR(255),
ADD COLUMN IF NOT EXISTS stripeIdentityAmountPaid INT;
