ALTER TABLE `siteSettings`
  ADD COLUMN `siteName` varchar(200) NULL AFTER `ogImage`,
  ADD COLUMN `siteUrl` varchar(500) NULL AFTER `siteName`,
  ADD COLUMN `twitterHandle` varchar(100) NULL AFTER `siteUrl`,
  ADD COLUMN `defaultMetaRobots` varchar(255) NULL AFTER `twitterHandle`,
  ADD COLUMN `homeSeoTitle` varchar(200) NULL AFTER `defaultMetaRobots`,
  ADD COLUMN `homeSeoDescription` text NULL AFTER `homeSeoTitle`,
  ADD COLUMN `marketplaceSeoTitle` varchar(200) NULL AFTER `homeSeoDescription`,
  ADD COLUMN `marketplaceSeoDescription` text NULL AFTER `marketplaceSeoTitle`,
  ADD COLUMN `createListingSeoTitle` varchar(200) NULL AFTER `marketplaceSeoDescription`,
  ADD COLUMN `createListingSeoDescription` text NULL AFTER `createListingSeoTitle`,
  ADD COLUMN `buyAssetSeoTitle` varchar(200) NULL AFTER `createListingSeoDescription`,
  ADD COLUMN `buyAssetSeoDescription` text NULL AFTER `buyAssetSeoTitle`,
  ADD COLUMN `pricingSeoTitle` varchar(200) NULL AFTER `buyAssetSeoDescription`,
  ADD COLUMN `pricingSeoDescription` text NULL AFTER `pricingSeoTitle`,
  ADD COLUMN `valuationToolSeoTitle` varchar(200) NULL AFTER `pricingSeoDescription`,
  ADD COLUMN `valuationToolSeoDescription` text NULL AFTER `valuationToolSeoTitle`,
  ADD COLUMN `verifyStripeSeoTitle` varchar(200) NULL AFTER `valuationToolSeoDescription`,
  ADD COLUMN `verifyStripeSeoDescription` text NULL AFTER `verifyStripeSeoTitle`;

UPDATE `siteSettings`
SET
  `siteName` = COALESCE(`siteName`, 'Acquisitions.market'),
  `siteUrl` = COALESCE(`siteUrl`, 'https://acquisitions.market'),
  `defaultMetaRobots` = COALESCE(`defaultMetaRobots`, 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'),
  `seoTitle` = COALESCE(`seoTitle`, 'Acquisitions.market | Digital Asset & Online Business Marketplace'),
  `seoDescription` = COALESCE(`seoDescription`, 'Browse digital assets, online businesses, and acquisition opportunities. Protect confidential information, qualify buyers, and move deals forward.'),
  `homeSeoTitle` = COALESCE(`homeSeoTitle`, 'Acquisitions.market | Digital Asset & Online Business Marketplace'),
  `homeSeoDescription` = COALESCE(`homeSeoDescription`, 'Browse digital assets, online businesses, and acquisition opportunities. Protect confidential information, qualify buyers, and move deals forward.'),
  `marketplaceSeoTitle` = COALESCE(`marketplaceSeoTitle`, 'Browse Acquisition Opportunities | Acquisitions.market'),
  `marketplaceSeoDescription` = COALESCE(`marketplaceSeoDescription`, 'Browse digital assets, online businesses, and other acquisition opportunities available on the marketplace.'),
  `createListingSeoTitle` = COALESCE(`createListingSeoTitle`, 'Create Listing | Acquisitions.market'),
  `createListingSeoDescription` = COALESCE(`createListingSeoDescription`, 'List a digital asset, online business, or acquisition opportunity for qualified buyers.'),
  `buyAssetSeoTitle` = COALESCE(`buyAssetSeoTitle`, 'Buyer Requests | Acquisitions.market'),
  `buyAssetSeoDescription` = COALESCE(`buyAssetSeoDescription`, 'Submit your acquisition criteria and connect with sellers looking for the right buyer.'),
  `pricingSeoTitle` = COALESCE(`pricingSeoTitle`, 'Pricing | Acquisitions.market'),
  `pricingSeoDescription` = COALESCE(`pricingSeoDescription`, 'Transparent success-based pricing for listing acquisition opportunities on Acquisitions.market.'),
  `valuationToolSeoTitle` = COALESCE(`valuationToolSeoTitle`, 'Business Valuation Tool | Acquisitions.market'),
  `valuationToolSeoDescription` = COALESCE(`valuationToolSeoDescription`, 'Estimate the value of a digital asset or online business using structured financial inputs.'),
  `verifyStripeSeoTitle` = COALESCE(`verifyStripeSeoTitle`, 'Identity Verification | Acquisitions.market'),
  `verifyStripeSeoDescription` = COALESCE(`verifyStripeSeoDescription`, 'Complete secure identity verification to unlock marketplace actions and protected information.');

INSERT INTO `siteSettings` (
  `siteName`,
  `siteUrl`,
  `defaultMetaRobots`,
  `seoTitle`,
  `seoDescription`,
  `ogTitle`,
  `ogDescription`,
  `homeSeoTitle`,
  `homeSeoDescription`,
  `marketplaceSeoTitle`,
  `marketplaceSeoDescription`,
  `createListingSeoTitle`,
  `createListingSeoDescription`,
  `buyAssetSeoTitle`,
  `buyAssetSeoDescription`,
  `pricingSeoTitle`,
  `pricingSeoDescription`,
  `valuationToolSeoTitle`,
  `valuationToolSeoDescription`,
  `verifyStripeSeoTitle`,
  `verifyStripeSeoDescription`
)
SELECT
  'Acquisitions.market',
  'https://acquisitions.market',
  'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1',
  'Acquisitions.market | Digital Asset & Online Business Marketplace',
  'Browse digital assets, online businesses, and acquisition opportunities. Protect confidential information, qualify buyers, and move deals forward.',
  'Acquisitions.market',
  'Marketplace infrastructure for acquisitions of digital assets and online businesses.',
  'Acquisitions.market | Digital Asset & Online Business Marketplace',
  'Browse digital assets, online businesses, and acquisition opportunities. Protect confidential information, qualify buyers, and move deals forward.',
  'Browse Acquisition Opportunities | Acquisitions.market',
  'Browse digital assets, online businesses, and other acquisition opportunities available on the marketplace.',
  'Create Listing | Acquisitions.market',
  'List a digital asset, online business, or acquisition opportunity for qualified buyers.',
  'Buyer Requests | Acquisitions.market',
  'Submit your acquisition criteria and connect with sellers looking for the right buyer.',
  'Pricing | Acquisitions.market',
  'Transparent success-based pricing for listing acquisition opportunities on Acquisitions.market.',
  'Business Valuation Tool | Acquisitions.market',
  'Estimate the value of a digital asset or online business using structured financial inputs.',
  'Identity Verification | Acquisitions.market',
  'Complete secure identity verification to unlock marketplace actions and protected information.'
WHERE NOT EXISTS (SELECT 1 FROM `siteSettings` LIMIT 1);
